spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server :
  port: 8081

jwt:
  secret: VGVzdC1Kd3QtU2VjcmV0LUtleS1Gb3ItQXV0aC1TZXJ2aWNlLTEyMzQ1Njc4
  access-token-expiration: 900000
  refresh-token-expiration: 604800000