spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server :
  port: 8081

jwt:
  secret: my-super-secret-key
  access-token-expiration: 900000      # 15 mins
  refresh-token-expiration: 604800000  # 7 days